### PR TITLE
Reinit

### PR DESCRIPTION
**Pull request by kenoss**
Re-initialize this repository.

This PR contains lots of changes @laysakura and @kenoss recently did in `actfw-jetson`.

- Use poetry instead of pipenv.
- Introduce pysen https://github.com/Idein/actfw-jetson/pull/10
- Rearrange directory hierarchy https://github.com/Idein/actfw-jetson/pull/12
- Update `.gitignore`.
- Minimize CI config with `actfw-jetson`, e.g. https://github.com/Idein/actfw-jetson/pull/7 https://github.com/Idein/actfw-jetson/pull/9 https://github.com/Idein/actfw-jetson/pull/11
- [Breaking change] Make not to export `version` https://github.com/Idein/actfw-jetson/pull/5

I turned off flake8 and mypy. It'll take lots of work.

Strictly speaking, the next release should be a major version up since there's a breaking change.

### CODE REVIEW

**Review by laysakura — DISMISSED** [review]
Changes seems OK to me.

> I turned off flake8 and mypy. It'll take lots of work.

Got it.

> [Breaking change] Make not to export version Idein/actfw-jetson#5
> Strictly speaking, the next release should be a major version up since there's a breaking change.

Agree with you. Next version should be v2.0.0.

@notogawa (as a maintainer)
How do you think?

**Comment by notogawa** [comment]
> * Update .gitignore.

Is https://github.com/Idein/actfw-core/pull/10/commits/d1e2452a1f9c2d9c27d065e07495ef380a98edb1 what you (≠ sphinx) want ?

> How do you think?

agree

**Comment by kenoss** [comment]
> Is d1e2452 what you (≠ sphinx) want ?

Yes. IIUC, the comment

```
# auto-generated by sphinx (should be commited only in gh-pages branch)
docs/*.rst
!docs/index.rst
```

means "bellow files are auto-generated by sphinx, so ignore for safety except gh-pages branch"; does not mean "these lines are auto-generated."

**Review by notogawa — APPROVED** [review]
LGTM

**Comment by kenoss** [comment]
We argued at discord.

@notogawa 's point is not the above, and is "we should share .gitgignore do not rely on .gitignore_global of each member, on not."
Our conclusion is we adopt the latter for `actfw-*` repositories at this time.

**Pull request merged**
